# This template gets rendered using `loop: "{{ molecule_yml.platforms }}"`, so
# each `item` is an element of platforms list from the molecule.yml file for this scenario.
FROM {{ item.image }}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       sudo \
       bash \
       python3 \
       software-properties-common \
       rsyslog \
       systemd systemd-cron \
    && apt-get clean \
    && rm -Rf /usr/share/doc \
    && rm -Rf /usr/share/man \
    && rm -rf /var/lib/apt/lists/* \
    && touch -d "2 hours ago" /var/lib/apt/lists
RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

RUN rm -f /lib/systemd/system/systemd*udev* \
  && rm -f /lib/systemd/system/getty.target

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
