---
dependency:
  name: galaxy
  options:
    requirements-file: ./molecule/resources/collections.yml

driver:
  name: containers

platforms:
  - name: molecule-debian-buster
    image: docker.io/debian:buster
    pre_build_image: false
    groups:
      - debian
      - systemd

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
