---
dependency:
  name: galaxy
  options:
    requirements-file: ./molecule/resources/collections.yml

driver:
  name: containers

platforms:
  - name: molecule-archlinux
    image: ghcr.io/stegmannb/container-archlinux-ansible:latest
    pre_build_image: true
    groups:
      - archlinux

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
