---
variables:
  ROLE_NAME: template

stages:
  - test
  - git-robot

pre-commit:
  stage: test
  image: python:buster
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ${CI_PROJECT_DIR}/.cache/
  before_script:
    - python3 -m pip install pre-commit
    - python3 --version
    - pre-commit --version
  script:
    - >-
      pre-commit run
      --files $(git diff-tree --no-commit-id --name-only -m -r "$CI_COMMIT_SHA")

molecule:
  stage: test
  image: docker:stable-dind
  services:
    - name: docker:dind
  tags:
    - docker
  variables:
    PY_COLORS: "1"
    ANSIBLE_FORCE_COLOR: "1"
  before_script:
    - apk add --no-cache
      python3 python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh
    - python3 -m pip install ansible molecule[docker] ansible-lint yamllint flake8
    - cd ../
    - mv $CI_PROJECT_DIR ${CI_PROJECT_DIR}.${ROLE_NAME}
    - mkdir -p ${CI_PROJECT_DIR}/roles
    - mv ${CI_PROJECT_DIR}.${ROLE_NAME} ${CI_PROJECT_DIR}/roles/${ROLE_NAME}
    - cd ${CI_PROJECT_DIR}/roles/${ROLE_NAME}
    - docker --version
    - python3 --version
    - ansible --version
    - yamllint --version
    - molecule --version
  script:
    - molecule test
  except:
    changes:
      - README.md
      - ".pre-commit-config.yaml"

git-merge-to-master:
  stage: git-robot
  image: debian:buster
  only:
    - dev
  allow_failure: false
  before_script:
    - git config --global user.email "robot@leitnet.at"
    - git config --global user.name "Mr. Robot"
    - mkdir -p ~/.ssh
    - ssh-keyscan gitlab.com >> gitlab-known-hosts
    - cat gitlab-known-hosts >> ~/.ssh/known_hosts
    - echo "$CI_REPOSITORY_URL"
    - echo "$CI_PROJECT_URL"
    - echo "$CI_PROJECT_PATH"
    - echo "$CI_PROJECT_PATH_SLUG"
  script:
    - git clone https://${CI_DEPLOY_USER}:${CI_DEPLOY_PASSWORD}:@${CI_REPOSITORY_URL}
    - cd ${CI_PROJECT_NAME}
    - git merge origin/dev
    - git push origin master
