---
exclude: |
  (?x)^(
      .vscode/.*|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        exclude: package-lock.json
      - id: detect-private-key
      - id: check-symlinks
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: remove-tabs

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
        name: yamllint
        description: This hook runs yamllint.
        entry: yamllint --strict
        language: python
        types: [file, yaml]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.24.0
    hooks:
      - id: markdownlint
        name: markdownlint
        description: "Checks the style of Markdown/Commonmark files."
        entry: markdownlint
        language: node
        types: [markdown]
        minimum_pre_commit_version: 0.15.0

  - repo: https://github.com/ansible/ansible-lint
    rev: v4.3.5
    hooks:
      - id: ansible-lint
        name: Ansible-lint
        description: This hook runs ansible-lint.
        entry: ansible-lint --force-color -x 106
        language: python
        # do not pass files to ansible-lint, see:
        # https://github.com/ansible/ansible-lint/issues/611
        pass_filenames: false
        always_run: true

  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v0.1.2
    hooks:
      - id: encryption-check
        name: Ansible Vault Encryption Check
        description: Checks that vault files are encrypted
        entry: encryption-check.sh
        files: ((^|/)vault|vault.y[a]{0,1}ml$|.vault$)
        language: script

  - repo: https://github.com/prettier/pre-commit
    rev: v2.2.0
    hooks:
      - id: prettier
        name: prettier
        entry: |
          prettier
          --write
          --list-different
          --ignore-unknown
        language: node
        exclude: |
          (?x)^(
              .vscode/|
          )$

  - repo: https://github.com/robertdebock/pre-commit
    rev: v1.1.2
    hooks:
      - id: ansible_role_find_unused_variable

  - repo: https://github.com/robertdebock/pre-commit
    rev: v1.1.2
    hooks:
      - id: ansible_role_find_empty_files
