---
dependency:
  name: galaxy
  options:
    requirements-file: ./molecule/resources/collections.yml

driver:
  name: vagrant
  provider:
    name: libvirt
    options:
      memory: 512
      cpus: 2

platforms:
  - name: molecule-archlinux
    box: archlinux/archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - archlinux

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
