---
# this role has no ansible-galaxy dependencies
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
platforms:
  - name: build-ubuntu-noble-systemd
    image: docker.io/ubuntu:20.04
    groups:
      - debian
      - systemd
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    systemd: true
    vars:
      ansible_os_family: Debian
provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
