# This template gets rendered using `loop: "{{ molecule_yml.platforms }}"`, so
# each `item` is an element of platforms list from the molecule.yml file for this scenario.
FROM {{ item.image }}

{% if "alpine" in item.groups %}
RUN apk add --no-cache \
            sudo \
            bash
{% endif %}
