---
# this role has no ansible-galaxy dependencies
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
platforms:
  - name: debian-bullseye
    image: mirror.gcr.io/debian:bullseye
    vars:
      ansible_os_family: Debian

provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
