---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    options:
      memory: 512
      cpus: 2

platforms:
  - name: test-updaterserver-ubuntu2204
    box: generic/ubuntu2204
    memory: 1024 # The machine does not start with less memory
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - ubuntu
  - name: test-updaterserver-ubuntu2004
    box: generic/ubuntu2004
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - ubuntu
  - name: test-updaterserver-debian11
    box: generic/debian11
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - debian
  - name: test-updaterserver-debian10
    box: generic/debian10
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - debian
  - name: test-updaterserver-arch
    box: archlinux/archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - archlinux

provisioner:
  name: ansible

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
