---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    options:
      memory: 512
      cpus: 2

platforms:
  - name: molecule-jammy
    box: generic/ubuntu2204
    memory: 1024 # The machine does not start with less memory
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - ubuntu
  - name: molecule-focal
    box: generic/ubuntu2004
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - ubuntu
  - name: molecule-bullseye
    box: generic/debian11
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - debian
  - name: molecule-buster
    box: generic/debian10
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - debian
  - name: molecule-archlinux
    box: archlinux/archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - archlinux
  - name: molecule-alpine
    box: generic/alpine312
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - alpine

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
