---
dependency:
  name: galaxy
  options:
    requirements-file: ./molecule/resources/collections.yml

driver:
  name: containers

platforms:
  - name: molecule-debian-systemd-buster
    image: ghcr.io/stegmannb/container-debian-ansible:buster
    pre_build_image: true
    groups:
      - debian
      - systemd
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
