---
dependency:
  name: galaxy
  options:
    requirements-file: ./molecule/resources/collections.yml

driver:
  name: containers

platforms:
  - name: molecule-ubuntu-systemd-jammy
    image: docker.io/eniocarboni/docker-ubuntu-systemd:jammy
    pre_build_image: true
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - ubuntu

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
