---
dependency:
  name: galaxy

driver:
  name: containers

platforms:
  - name: molecule-archlinux
    image: docker.io/archlinux/archlinux
    pre_build_image: false
    groups:
      - archlinux

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
