---
dependency:
  name: galaxy

driver:
  name: containers

platforms:
  - name: molecule-fedora-37
    image: docker.io/fedora:37
    pre_build_image: true
    groups:
      - fedora
  - name: molecule-fedora-36
    image: docker.io/fedora:36
    pre_build_image: true
    groups:
      - fedora
  - name: molecule-alpine-3
    image: docker.io/alpine:3
    pre_build_image: false
    groups:
      - alpine
  - name: molecule-archlinux
    image: docker.io/archlinux:latest
    pre_build_image: true
    groups:
      - archlinux
  - name: molecule-ubuntu-jammy
    image: docker.io/ubuntu:jammy
    pre_build_image: true
    groups:
      - ubuntu
  - name: molecule-ubuntu-focal
    image: docker.io/ubuntu:focal
    pre_build_image: true
    groups:
      - ubuntu
  - name: molecule-ubuntu-bionic
    image: docker.io/ubuntu:bionic
    pre_build_image: true
    groups:
      - ubuntu
  - name: molecule-debian-bullseye
    image: docker.io/debian:bullseye
    pre_build_image: true
    groups:
      - debian
  - name: molecule-debian-buster
    image: docker.io/debian:buster
    pre_build_image: true
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
