---
dependency:
  name: galaxy

driver:
  name: containers

platforms:
  - name: molecule-alpine
    image: docker.io/alpine:latest
    pre_build_image: false
    groups:
      - alpine

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
