---
dependency:
  name: galaxy

driver:
  name: containers

platforms:
  - name: molecule-ubuntu-focal
    image: docker.io/ubuntu:focal
    pre_build_image: true
    groups:
      - ubuntu

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
