---
- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Converge
  hosts: molecule
  tasks:
    - name: Debug
      ansible.builtin.copy:
        dest: facts-{{ inventory_hostname }}.json
        content: "{{ ansible_facts | to_nice_json }}"
      delegate_to: localhost
      changed_when: false

    - name: Run the role
      ansible.builtin.import_role:
        name: stegmannb.template
