---
- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        children:
          molecule:
            hosts: {}

  tasks:
    - name: Check if the Containerfile exists
      ansible.builtin.stat:
        path: "../../{{ molecule_yml.scenario.name }}/Containerfile"
      register: _containerfile
      delegate_to: localhost

    - name: Build the test container
      containers.podman.podman_image:
        name: "{{ item.name }}"
        path: ../../{{ molecule_yml.scenario.name }}
        build:
          extra_args: "--build-arg image={{ item.image }}"
      loop: "{{ molecule_yml.platforms }}"
      when: _containerfile.stat.exists

    - name: Create a container
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.name if _containerfile.stat.exists else item.image }}"
        privileged: "{{ item.privileged | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        capabilities: "{{ item.capabilities | default(omit) }}"
        systemd: "{{ item.systemd | default(omit) }}"
        state: started
        command: "{{ item.command | default('sleep 1d') }}"
        # bash -c "while true; do sleep 10000; done"
        log_driver: json-file
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Print container info
      ansible.builtin.debug:
        msg: "{{ result.results }}"
        verbosity: 2

    - name: Fail if container is not running
      when: >
        item.container.State.ExitCode != 0 or
        not item.container.State.Running
      ansible.builtin.fail:
        msg: "Container '{{ item.container.Name }}' is not running"
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.container.Name }}"

    - name: Add container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                hosts:
                  "{{ item.name }}":
                    ansible_connection: containers.podman.podman
          {% for key in item.vars %}
                    {{ key }}: "{{ item.vars[key] }}"
          {% endfor %}
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Force inventory refresh
      ansible.builtin.meta: refresh_inventory

    - name: Fail if molecule group is missing
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}
        quiet: true
      run_once: true # noqa: run-once[task]

# we want to avoid errors like "Failed to create temporary directory"
- name: Install Python
  hosts: molecule
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false
  tasks:
    - name: Setup python
      ansible.builtin.include_tasks:
        file: setup-python-{{ ansible_os_family | lower }}.yml
