---
"on":
  pull_request:
  push:

defaults:
  run:
    working-directory: "stegmannb.template"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: requirements-dev.txt

      - uses: pre-commit/action@v2.0.0

  molecule-containers:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - container-alpine
          - container-archlinux
          - container-debian-bullseye
          - container-debian-buster
          - container-ubuntu-bionic
          - container-ubuntu-focal
          - container-ubuntu-jammy
    steps:
      - name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@master

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "${{ github.repository }}/requirements-dev.txt"

      - name: Install pip requirements
        run: pip install -r requirements-dev.txt
        working-directory: "${{ github.repository }}"

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
          molecule_working_dir: "${{ github.repository }}"
        env:
          ANSIBLE_FORCE_COLOR: "1"

  molecule-vagrant:
    needs:
      - pre-commit
    runs-on: vagrantlibvirt/vagrant-libvirt
    # strategy:
    #   matrix:
    #     scenario:
    # - vagrant-alpine
    # - vagrant-archlinux
    # - vagrant-debian-bullseye
    # - vagrant-debian-buster
    # - vagrant-ubuntu-focal
    # - vagrant-ubuntu-jammy
    steps:
      - name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@master

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "${{ github.repository }}/requirements-dev.txt"

      - name: Install pip requirements
        run: pip install -r requirements-dev.txt
        working-directory: "${{ github.repository }}"

      # - name: Cache Vagrant boxes
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.vagrant.d/boxes
      #     key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
      #     restore-keys: |
      #       ${{ runner.os }}-vagrant-

      - name: Molecule Run Vagrant
        run: molecule test --scenario-name vagrant-alpine
        working-directory: "${{ github.repository }}"

      - name: Molecule Action Vagrant
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name vagrant-alpine
          molecule_working_dir: "${{ github.repository }}"
