---
"on":
  pull_request:
  push:

defaults:
  run:
    working-directory: "stegmannb.template"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: requirements-dev.txt

      - uses: pre-commit/action@v3.0.0

  molecule:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - alpine
          - archlinux-systemd
          - archlinux
          - debian-systemd-bookworm
          - debian-systemd-bullseye
          - debian-systemd-buster
          - debian-bookworm
          - debian-bullseye
          - debian-buster
          - ubuntu-systemd-jammy
          - ubuntu-systemd-focal
          - ubuntu-systemd-bionic
          - ubuntu-jammy
          - ubuntu-focal
          - ubuntu-bionic
    steps:
      - name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@master

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "${{ github.repository }}/requirements-dev.txt"

      - name: Install pip requirements
        run: pip install -r requirements-dev.txt
        working-directory: "${{ github.repository }}"

      - name: Molecule Version
        run: molecule --version
        working-directory: "${{ github.repository }}"

      - name: Molecule test
        run: molecule test --scenario-name ${{ matrix.scenario }}
        working-directory: "${{ github.repository }}"

  # molecule-vagrant:
  #   needs:
  #     - pre-commit
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       scenario:
  #         - vagrant-alpine
  #         - vagrant-archlinux
  #         - vagrant-debian-bullseye
  #         - vagrant-debian-buster
  #         - vagrant-ubuntu-focal
  #         - vagrant-ubuntu-jammy
  #   steps:
  #     - name: Cancel an already running workflow.
  #       uses: fkirc/skip-duplicate-actions@master

  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         path: "${{ github.repository }}"

  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.11.2"
  #         cache: "pip" # caching pip dependencies
  #         cache-dependency-path: "${{ github.repository }}/requirements-dev.txt"

  #     - name: Install pip requirements
  #       run: pip install -r requirements-dev.txt
  #       working-directory: "${{ github.repository }}"

  #     - name: Install vagrant
  #       run: |
  #         wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  #         echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  #         sudo apt-get update
  #         sudo apt-get install -y vagrant
  #       working-directory: "${{ github.repository }}"

  #     - name: Install VirtualBox
  #       run: |
  #         sudo apt-get install -y virtualbox
  #       working-directory: "${{ github.repository }}"

  #     # - name: Cache Vagrant boxes
  #     #   uses: actions/cache@v2
  #     #   with:
  #     #     path: ~/.vagrant.d/boxes
  #     #     key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
  #     #     restore-keys: |
  #     #       ${{ runner.os }}-vagrant-

  #     - name: Molecule test
  #       run: molecule test --scenario-name ${{ matrix.scenario }}
  #       working-directory: "${{ github.repository }}"
