---
"on":
  pull_request:
  push:

defaults:
  run:
    working-directory: "stegmannb.template"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: requirements-dev.txt
      - uses: pre-commit/action@v2.0.0

  molecule:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - container-alpine
          - container-archlinux
          - container-debian-bullseye
          - container-debian-buster
          - container-ubuntu-bionic
          - container-ubuntu-focal
          - container-ubuntu-jammy
          - vagrant-alpine
          - vagrant-archlinux
          - vagrant-debian-bullseye
          - vagrant-debian-buster
          - vagrant-ubuntu-focal
          - vagrant-ubuntu-jammy
    steps:
      - name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@master

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run molecule tests
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
