---
"on":
  pull_request:
  push:

defaults:
  run:
    working-directory: "stegmannb.template"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: requirements-dev.txt
      - uses: pre-commit/action@v2.0.0

  molecule:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - ubuntu1804
          - fedora33
          - fedora32
          - debian10
          - debian9
    steps:
      - name: Cancel an already running workflow.
        uses: fkirc/skip-duplicate-actions@master

      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          molecule_working_dir: "${{ github.repository }}"

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
